version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mysql


  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sql_injection
      MYSQL_USER: sql_injection
      MYSQL_PASSWORD: inject
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
