version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: inject
      POSTGRES_DB: sql_injection
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d